# Generated by Django 4.2.1 on 2023-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buoys',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buoys',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='buoy',
        ),
    ]
