# Generated by Django 4.2.1 on 2023-05-27 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_buoys_location_remove_buoys_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
