# Generated by Django 4.2.1 on 2023-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ship_created_at_ship_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoys',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='Small', max_length=10),
            preserve_default=False,
        ),
    ]
