# Generated by Django 4.2.1 on 2023-05-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_buoys_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
    ]
