# Generated by Django 4.2.1 on 2023-05-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_buoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoys',
            name='price1',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buoys',
            name='price2',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
